config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "homes#index"

  resource :experiences, only: [:show]
  resource :photos, only: [:show]
  resource :portfolios, only: [:show]
  resource :who_i_ams, only: [:show]
  resource :knowledges, only: [:show]
  resource :estimates, only: [:show]
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/estimate.rb
class Estimate < ApplicationRecord
end

app/models/experience.rb
class Experience < ApplicationRecord
end

app/models/index.rb
class Index < ApplicationRecord

end

app/models/knowledge.rb
class Knowledge < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/models/photos.rb
class Photo < ApplicationRecord
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/who_i_am.rb
class WhoIAm < ApplicationRecord
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  def show
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def show
  end
end

app/helpers/acceuil_helper.rb
module AcceuilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devis_helper.rb
module DevisHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/galeries_helper.rb
module GaleriesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/qui_suis_jes_helper.rb
module QuiSuisJesHelper
end

app/helpers/savoirs_helper.rb
module SavoirsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>MaximeRDB-CV</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="short cut icon" href="img/Gold.jpeg">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>


    <header>
      <%= render "shared/nav_bar" %>
    </header>

      <%= render "shared/banner" %>

    <div class="container-for-body">
      <%= yield %>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

  <footer>
    <%= render "shared/footer" %>
  </footer>

</html>

app/views/savoir_faire/savoir_faire.html.erb
        <div class="langues">
        <h2>LANGUES</h2>
        <ul>
          <li>FRANÇAIS - langue maternelle</li>
          <li>ANGLAIS - B2</li>
          <li>ESPAGNOL - A2</li>
        </ul>
      </div>
<br>

       <div class="DIPLÔMES">
        <h2>DIPLÔMES</h2>

           <strong>BAC PRO RESTAURANT</strong><br>
            CFA SERVICE & COMMERCE BLAGNAC, FRANCE
            TOULOUSE & MURET <br>
<br>

           <strong>CAP COMMERCIALISATION ET SERVICES</strong> <br>
            EN HÔTEL-CAFÉ-RESTAURANT
            CFA SERVICE & COMMERCE BLAGNAC, FRANCE <br>
            <br>
            Permis B et A1 &#128692 <br>
            <br>
       </div>
          <div class="exp">
            <br>
              <h2> <strong>EXPÉRIENCES</strong></h2>
            <ul>
              <br>
              <li><strong>Juin 2022 à Aujourd'hui</strong><br>
              CHEF DE PARTIE PIZZAÏOLO
            PRIMA DES COLONNES, BIARRITZ <br>
De la pâte à la production.</li>
<br>
              <li><strong>Septembre 2022 à Juin 2022</strong><br>
              DIRECTEUR D'EXPLOITATION
              LA GRANDE PIZZERIA, TOULOUSE. <br>
              Gestion générale.
              </li>
              <br>
              <li> <strong>Août 2020 à Septembre 2022</strong><br>
                DIRECTEUR ADJOINT
                LES 4 SAISONS,TOULOUSE <br>
                Gestion du restaurant, des commandes et formation de deux apprentis.
              </li>
              <br>
<li> <strong>Septembre 2019 à Mars 2020</strong><br>
  RESPONSABLE DE SALLE ET SERVEUR
  TRAMSHED RESTAURANT, LONDRES, ANGLETERRE <br>
  Service, ouverture et fermeture des caisses et du
  restaurant. Responsable des commandes en salle. Gestion d'une équipe et co-working.
  Formation des jeunes serveurs.
  </li>
  <br>
  <li> <strong>Août 2018 à Août 2019</strong> <br>
    DIRECTEUR ADJOINT
    LA GRANDE PIZZERIA, TOULOUSE <br>
    Construction des menus en collaboration avec le chef de 2019 cuisine, fixation des prix, gestion produits, rotation des
    plannings. Recrutement, formation, gestion d’une équipe de plus de 10 serveurs/serveuses, travail de communication en équipe.</li>
          <br>
    <li> <strong>Avril 2018 à Juin 2018</strong><br>
            SERVEUR
            MONLI RESTAURANT, PUERTO VIEJO, COSTA RICA <br>
            Prise de commandes, bar, explication du menu en
            Français, Anglais & Espagnol.</li>
            <br>
            <li><strong>Octobre 2016 à Octobre 2017</strong><br>
              SERVEUR / AIDE BARMAN / BARMAN <br>
              GROUPE MÉRIVAL, M’S G’S, FISH SHOP
              RESTAURANT, SYDNEY, AUSTRALIE <br>
              2017 Runner, service, accueil, aide barman, élaboration des
              cocktails</li> <br>
  </ul>
    </div>
    </section>

app/views/shared/_banner.html.erb
 <div>
    <%= image_tag "back_ground.jpeg", class: "banner", style: "background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))" %>
  </div>

app/views/shared/_cards_about.html.erb
<div class="container_me">

    <div class="title_about col-6 pt-2 pl-3">
        <h1>
          Bonjour <br>
          Je m'appelle <br>
          Maxime Rollinde de Beaumont
        </h1>
    </div>

    <div class="text_about col-6 pt-3">
      <p>
        Motivé, Studieux, Autonome et aime le travail en équipe.
        Avec de bonnes connaissances sur le travail d’entreprise, je sais
        m’adapter à des situations de stress et suis à l’écoute.
        Je suis capable d’innover, proposer des idées et amener une
        bonne énergie.
      </p>
    </div>

</div>


<div class="container_me">

    <div class="title_about ol-6 px-3">
        <h1>Intérêt</h1>
    </div>

    <div class="text_about col-6 pt-2">
        <p>
          J'aime beaucoup la musique et notament en faire : <br>
          Je fait du piano et de la guitare en auto-didacte.
        </p> <br>
        <p> ÉCLAIREURS DE FRANCE / Branche du scoutisme laïc (DEPUIS 2001), DIVERS SPORTS<br></p>
    </div>

</div>


<div class="container_me">

    <div class="title_about ol-6 px-3">
      <h1>VOYAGES</h1>
    </div>

    <div class="text_about col-6 pt-2">
      <p>Cambodge, Espagne, Costa Rica,
        Panama, Colombie, Portugal,
        Grèce, Autriche, Irlande,
        Pologne, Allemagne, Turqui,
        Italie, Chine, Australie, Pays-Bas,
        États-Unis, Angletter.
      </p>
    </div>

</div>

app/views/shared/_cards_accueil.html.erb
<div class="cards">

  <div class="card-category">
    <%= link_to who_i_ams_path do %>
      <%= image_tag "MaxPic.JPG", class: "card-category", style: "linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"%>
    <% end %>
    <p class="card_title">About</p>
  </div>

  <div class="card-category">
    <%= link_to knowledges_path do %>
      <%= image_tag "montagne.jpg", class: "card-category", style: "linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"%>
    <% end %>
    <p class="card_title">Knowledge</p>
  </div>

  <div class="card-category">
    <%= link_to experiences_path do %>
      <%= image_tag "Gold.jpeg", class: "card-category", style: "linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"%>
    <% end %>
    <p class="card_title">Resume</p>
  </div>

  <div class="card-category">
    <%= link_to photos_path do %>
      <%= image_tag "galaxie.jpeg", class: "card-category", style: "linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"%>
    <% end %>
    <p class="card_title">Photos</p>
  </div>

  <div class="card-category">
    <%= link_to portfolios_path do %>
      <%= image_tag "sweet.jpg", class: "card-category", style: "linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"%>
    <% end %>
    <p class="card_title">Portfolio</p>
  </div>

  <div class="card-category">
    <%= link_to estimates_path do %>
      <%= image_tag "fête.jpeg", class: "card-category", style: "linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"%>
    <% end %>
    <p class="card_title">Estimate</p>
  </div>
  
</div>

app/views/shared/_carousel.html.erb
<div id="carouselExample" class="carousel slide" data-ride="carousel">

  <div class="carousel-inner">

    <div class="carousel-item active">
      <%= image_tag "fermier.png", class: "d=block w-100", alt: "Slide 1"%>
    </div>

    <div class="carousel-item">
      <%= image_tag "ninja.png", class: "d=block w-100", alt: "Slide 1"%>
    </div>

    <div class="carousel-item">
      <%= image_tag "badass.png", class: "d=block w-100", alt: "Slide 1"%>
    </div>

  </div>

  <a class="carousel-control-prev" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>

  <a class="carousel-control-next" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>CONTACT</p>
  <div class="container">
    <div class= "row">
      <div class="col-4">
        <a href="https://www.linkedin.com/in/maxime-rollinde-de-beaumont-2520b41ab/"><%= image_tag("Linkedin.png", class: "img") %></a>
      </div>
      <div class="col-4">
        <a href="https://github.com/MaximeRDB"><%= image_tag("Githublogo.png", class: "img") %></a> <br>
      </div>
      <div class="col-4">
        <a href="mailto:Maximerdb@hotmail.fr"><%= image_tag("lettre.webp", class: "img") %></a> <br>
      </div>
    </div>
    <p> ©2024 Rollinde de Beaumont Maxime Si vous avez besoin de plus d'informations, je vous invite à me contacter via les liens.</p>
  </div>
</div>

app/views/shared/_head_bar.html.erb
<div >
  <h1 class="A"><strong> Curriculum Vitae</strong></h1><br>
  <%= image_tag("MaxPic.JPG", class: "profil") %>
</div>

app/views/shared/_info_perso.html.erb
<p> Rollinde de Beaumont </p>
<p> Maxime</p>
<p class="dob">  15/10/1995 Prey-Veng, Cambodge 🇰🇭 <br>
                Nationalité : Française <br></p>

app/views/shared/_know.html.erb
<div class="container_me">

  <div class="title_about col-6 pt-2 pl-3">
    <h1> Frontend 🖥️ </h1>
  </div>

  <div class="text_about col-6 pt-3">

    <p> HTML, CSS, SCSS, JavaScript et Stimulus
      Savoir faire : <br>
      Responsive Design <br>
      UI & UX Design
    </p>
  </div>

</div>

<div class="container_me">

  <div class="title_about col-6 pt-2 pl-3">
    <h1> Backend 👨‍💻 </h1>
  </div>

  <div class="text_about col-6 pt-3">

    <p> Ruby 3, Ruby on Rails 7, Python 3 et SQL (Postgres, SQlite)
      Savoir faire : <br>
      Construire et travailler avec les APIs
    </p>
  </div>

</div>

<div class="container_me">

  <div class="title_about col-6 pt-2 pl-3">
    <h1> Outils 🛠️ </h1>
  </div>

  <div class="text_about col-6 pt-3">
    <p> Trello, Figma, Cloudinary, Postman, Excalidraw </p>
  </div>

</div>

<div class="container_me">

  <div class="title_about col-6 pt-2 pl-3">
    <h1> Notions 🧑‍🎓 </h1>
  </div>

  <div class="text_about col-6 pt-3">
    <p> Vue.JS, Moustache et Shell</p>
  </div>

</div>

<div class="container_me">

  <div class="title_about col-6 pt-2 pl-3">
    <h1> DevOps 👨‍💼 </h1>
  </div>

  <div class="text_about col-6 pt-3">
    <p> Heroku et Git / GitHub</p>
  </div>

</div>

app/views/shared/_nav_bar.html.erb
<div class="bandeau">

  <div class="raw d-flex justify-content-between text-center py-4">

    <div class="col-4">
      <nav>
        <details>
        <summary class="dm">More</summary>
          <ul>
            <li> <%= link_to "Home", root_path %> </li>
            <li> <%= link_to "About", who_i_ams_path %> </li>
            <li> <%= link_to "Knowledge", knowledges_path %> </li>
            <li> <%= link_to "Resume", experiences_path %> </li>
            <li> <%= link_to "Photos", photos_path %> </li>
            <li> <%= link_to "Portfolio", portfolios_path %> </li>
            <li> <%= link_to "Estimate", estimates_path %> </li>
          </ul>
        </details>
      </nav>
    </div>

    <div class="col-4">
      <h1 class="title"><%= link_to "ROLLINDE DE BEAUMONT MAXIME", root_path, class: "title" %> </h1>
    </div>

    <div class="col-4">
      <p><%= image_tag ("MaxPic.JPG"), class: "logo"%></p>
    </div>

  </div>

</div>